	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, YELLOW
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, BROWN, WATER, GREEN, BROWN, GREEN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, GRAY, BROWN, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF
	tilepal 0, ROOF, ROOF, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF
	tilepal 0, ROOF, ROOF, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, WATER, GRAY, BROWN, ROOF, ROOF
	tilepal 0, ROOF, ROOF, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, GRAY, BROWN, BROWN, RED, BROWN, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, YELLOW, YELLOW, YELLOW, GRAY, BROWN, GRAY
	tilepal 1, GRAY, BROWN, ROOF, BROWN, WATER, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, GRAY, BROWN, BROWN, GRAY, BROWN, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, BROWN
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, BROWN
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED
	tilepal 1, GRAY, GRAY, GRAY, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY
